# Generated by Django 3.2.5 on 2021-11-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
