# Generated by Django 3.2.5 on 2021-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibraryapp', '0003_books_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
